<a href="https://colab.research.google.com/github/siri2511/Python/blob/main/Numpy.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

### **Introduction to Numpy**

In [1]:
#importing numpy
import numpy as np

In [2]:
#creating 1d array
student_marks_arr = np.array([78,92,36,64,89])
student_marks_arr

array([78, 92, 36, 64, 89])

In [3]:
#creating list of 5 horsepower values
horsepower = [130, 165, 150, 150, 140]

#creating aa numpy array from horsepower list
horsepower_arr = np.array(horsepower)
horsepower_arr

array([130, 165, 150, 150, 140])

In [5]:
#creating a list of lists of 5 mpg, horsepower and acceleration values
car_attributes = [[18, 15, 18, 16, 17],[130, 165, 150, 150, 140],[307, 350, 318, 304, 302]]
#creating numpy array from car_attributes list
car_attributes_arr=np.array(car_attributes)
car_attributes_arr

array([[ 18,  15,  18,  16,  17],
       [130, 165, 150, 150, 140],
       [307, 350, 318, 304, 302]])

In [6]:
#shape of an array
car_attributes_arr.shape

(3, 5)

In [7]:
#dtype of ndarray
car_attributes_arr.dtype

dtype('int64')

In [8]:
#changing dtype
#creating a list of lists of 5 mpg, horsepower and acceleration values
car_attributes = [[18, 15, 18, 16, 17],[130, 165, 150, 150, 140],[307, 350, 318, 304, 302]]
#creating numpy array from car_attributes list
car_attributes_arr=np.array(car_attributes,dtype='float')
print(car_attributes_arr)
print(car_attributes_arr.dtype)

[[ 18.  15.  18.  16.  17.]
 [130. 165. 150. 150. 140.]
 [307. 350. 318. 304. 302.]]
float64


### **Operations on Numpy Arrays**

### Accessing Array Elements

In [9]:
#accessing elements from 1d array
cars=np.array(['cheverolet chevelle malibu', 'buick skylark 320', 'plymouth satellite', 'amc rebel sst', 'ford torino'])

#accessing 2nd car from the array
cars[1]

np.str_('buick skylark 320')

In [11]:
#accessing elements from 2d array
car_names=np.array(['cheverolet chevelle malibu', 'buick skylark 320', 'plymouth satellite', 'amc rebel sst', 'ford torino'])
horsepower = [130, 165, 150, 150, 140]

car_hp_arr = np.array([car_names,horsepower])
car_hp_arr

array([['cheverolet chevelle malibu', 'buick skylark 320',
        'plymouth satellite', 'amc rebel sst', 'ford torino'],
       ['130', '165', '150', '150', '140']], dtype='<U26')

In [12]:
#accessing horsepower
car_hp_arr[0]

array(['cheverolet chevelle malibu', 'buick skylark 320',
       'plymouth satellite', 'amc rebel sst', 'ford torino'], dtype='<U26')

In [13]:
#accessing horsepower
car_hp_arr[1]

array(['130', '165', '150', '150', '140'], dtype='<U26')

In [14]:
#accessing second car
car_hp_arr[0,1]

np.str_('buick skylark 320')

In [15]:
#accessing name of the last car
car_hp_arr[0,-1]

np.str_('ford torino')

### Slicing

In [16]:
#slicing from 1d array
cars=np.array(['cheverolet chevelle malibu', 'buick skylark 320', 'plymouth satellite', 'amc rebel sst', 'ford torino'])

cars[1:4]

array(['buick skylark 320', 'plymouth satellite', 'amc rebel sst'],
      dtype='<U26')

In [18]:
#slicing from 2d array
car_names=np.array(['cheverolet chevelle malibu', 'buick skylark 320', 'plymouth satellite', 'amc rebel sst', 'ford torino'])
horsepower = [130, 165, 150, 150, 140]
acceleration = [18, 15, 18, 16, 17]

car_hp_acc_arr = np.array([car_names, horsepower, acceleration])
car_hp_acc_arr

array([['cheverolet chevelle malibu', 'buick skylark 320',
        'plymouth satellite', 'amc rebel sst', 'ford torino'],
       ['130', '165', '150', '150', '140'],
       ['18', '15', '18', '16', '17']], dtype='<U26')

In [19]:
#accessing name and horsepower
car_hp_acc_arr[0:2]

array([['cheverolet chevelle malibu', 'buick skylark 320',
        'plymouth satellite', 'amc rebel sst', 'ford torino'],
       ['130', '165', '150', '150', '140']], dtype='<U26')

In [20]:
#accessing name and horsepower of last two cars
car_hp_acc_arr[0:2, 3:5]

array([['amc rebel sst', 'ford torino'],
       ['150', '140']], dtype='<U26')

In [21]:
#accessing name, horsepower and acceleartion of first 3 cars
car_hp_acc_arr[0:3, 0:3]

array([['cheverolet chevelle malibu', 'buick skylark 320',
        'plymouth satellite'],
       ['130', '165', '150'],
       ['18', '15', '18']], dtype='<U26')

### Mean and Median

In [22]:
horsepower = [130, 165, 150, 150, 140]
horsepower_arr=np.array(horsepower)

#mean horsepower
np.mean(horsepower_arr)

np.float64(147.0)

In [23]:
#median horsepower
np.median(horsepower_arr)

np.float64(150.0)

### Min & Max

In [24]:
np.min(horsepower_arr)

np.int64(130)

In [25]:
np.max(horsepower_arr)

np.int64(165)

In [26]:
#finding index of min and max values
np.argmin(horsepower_arr)

np.int64(0)

In [27]:
np.argmax(horsepower_arr)

np.int64(1)

### Querying/Searching in an array

In [30]:
horsepower = [130, 165, 150, 150, 140]
horsepower_arr=np.array(horsepower)

x = np.where(horsepower_arr >=150)
#gives the indices
print(x)
#with indices values can be found
horsepower_arr[x]

(array([1, 2, 3]),)


array([165, 150, 150])

### Filtering Data

In [31]:
horsepower = [130, 165, 150, 150, 140]
horsepower_arr=np.array(horsepower)

filter_arr = horsepower_arr>135
newarr = horsepower_arr[filter_arr]

print(filter_arr)
print(newarr)

[False  True  True  True  True]
[165 150 150 140]


### sorting an array

In [32]:
horsepower = [130, 165, 150, 150, 140]
horsepower_arr=np.array(horsepower)

print('Original Array: ',horsepower_arr)
print('Sorted Array: ',np.sort(horsepower_arr))
print('Original Array after sorting : ',horsepower_arr)

Original Array:  [130 165 150 150 140]
Sorted Array:  [130 140 150 150 165]
Original Array after sorting :  [130 165 150 150 140]


In [33]:
horsepower = [130, 165, 150, 150, 140]
horsepower_arr=np.array(horsepower)

print('Original Array: ',horsepower_arr)
horsepower_arr.sort()
print('Original Array after sorting : ',horsepower_arr)

Original Array:  [130 165 150 150 140]
Original Array after sorting :  [130 140 150 150 165]


array.sort(): modifies the original array by default <br>
sort(array): does not modify the original array by default

### Vectorized operations

Numpy makes use of optimized, pre-compiled code to perform mathematical operations on each array element. This eliminates the need of using loops, thereby enhancing the performance. This process is called vectorization.

In [34]:
student_marks_arr=np.array([78, 92, 36, 64, 89])
print(np.sum(student_marks_arr))

359


In [35]:
#award extra marks in each subject
additional_marks = [2,2,5,10,1]
student_marks_arr+=additional_marks
student_marks_arr

array([80, 94, 41, 74, 90])

In [36]:
student_marks_arr=np.array([78, 92, 36, 64, 89])
additional_marks = [2,2,5,10,1]
student_marks_arr = np.add(student_marks_arr,additional_marks)
student_marks_arr

array([80, 94, 41, 74, 90])

### Broadcasting

In [38]:
array1=np.array([5,10,15])
array2=np.array([5])
#array2 is being streched to match array1 resulting in new array with the same shape as array1
array3=array1*array2
array3

array([25, 50, 75])

In [40]:
#students marks in 4 subjects
students_marks = np.array([[67, 45],[90, 92],[66, 72],[32, 40]])
students_marks

array([[67, 45],
       [90, 92],
       [66, 72],
       [32, 40]])

In [41]:
#adding 5 marks in 1st sub and 10 marks in 2nd sub
students_marks+=[5,10]
students_marks

array([[ 72,  55],
       [ 95, 102],
       [ 71,  82],
       [ 37,  50]])

### Image as a Numpy matrix

In [ ]:
import os.path
from skimage.io import imread
from skimage import data_dir
img = imread('Astronaut.jpg')

In [ ]:
#using matplotlib.pyplot to visualise the image
import matplotlib.pyplot as plt
plt.imshow(img)

In [ ]:
#viewing as matrix
print(img)

In [ ]:
#properties of image
print('Type of image: ',type(img))
print('Dimensions of image: ',img.ndim)
print('Shape of image: ',img.shape)

In [ ]:
#cutting the rocket out of the image
import os.path
from skimage.io import imread
from skimage import data_dir

#reading the astronaut image
img = imread(os.path.join(data_dir, 'astronaut.jpg'))

#slicing out the rocket
img_slice = img.copy()
img_slice=img_slice[0:300,360:480]
plt.figure()
plt.imshow(img_slice)

In [ ]:
#assigning the values corresponding to the sliced image as 0
img[0:300, 360:480,:]=0
plt.imshow(img)

In [ ]:
img_slice[np.greater_eql(img_slice[:,:,0],100)&np.less_equal(img_slice[:,:,0],150)]=0
plt.figure()
plt.imshow(img_slice)

In [ ]:
#replacing rocket back to its original place
img[0:300,360:480,:]=img_slice
plt.imshow(img)