<a href="https://colab.research.google.com/github/siri2511/Python/blob/main/Numpy.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

### **Introduction to Numpy**

In [ ]:
#importing numpy
import numpy as np

In [ ]:
#creating 1d array
student_marks_arr = np.array([78,92,36,64,89])
student_marks_arr

array([78, 92, 36, 64, 89])

In [ ]:
#creating list of 5 horsepower values
horsepower = [130, 165, 150, 150, 140]

#creating aa numpy array from horsepower list
horsepower_arr = np.array(horsepower)
horsepower_arr

array([130, 165, 150, 150, 140])

In [ ]:
#creating a list of lists of 5 mpg, horsepower and acceleration values
car_attributes = [[18, 15, 18, 16, 17],[130, 165, 150, 150, 140],[307, 350, 318, 304, 302]]
#creating numpy array from car_attributes list
car_attributes_arr=np.array(car_attributes)
car_attributes_arr

array([[ 18,  15,  18,  16,  17],
       [130, 165, 150, 150, 140],
       [307, 350, 318, 304, 302]])

In [ ]:
#shape of an array
car_attributes_arr.shape

(3, 5)

In [ ]:
#dtype of ndarray
car_attributes_arr.dtype

dtype('int64')

In [ ]:
#changing dtype
#creating a list of lists of 5 mpg, horsepower and acceleration values
car_attributes = [[18, 15, 18, 16, 17],[130, 165, 150, 150, 140],[307, 350, 318, 304, 302]]
#creating numpy array from car_attributes list
car_attributes_arr=np.array(car_attributes,dtype='float')
print(car_attributes_arr)
print(car_attributes_arr.dtype)

[[ 18.  15.  18.  16.  17.]
 [130. 165. 150. 150. 140.]
 [307. 350. 318. 304. 302.]]
float64


### **Operations on Numpy Arrays**

### Accessing Array Elements

In [ ]:
#accessing elements from 1d array
cars=np.array(['cheverolet chevelle malibu', 'buick skylark 320', 'plymouth satellite', 'amc rebel sst', 'ford torino'])

#accessing 2nd car from the array
cars[1]

np.str_('buick skylark 320')

In [ ]:
#accessing elements from 2d array
car_names=np.array(['cheverolet chevelle malibu', 'buick skylark 320', 'plymouth satellite', 'amc rebel sst', 'ford torino'])
horsepower = [130, 165, 150, 150, 140]

car_hp_arr = np.array([car_names,horsepower])
car_hp_arr

array([['cheverolet chevelle malibu', 'buick skylark 320',
        'plymouth satellite', 'amc rebel sst', 'ford torino'],
       ['130', '165', '150', '150', '140']], dtype='<U26')

In [ ]:
#accessing horsepower
car_hp_arr[0]

array(['cheverolet chevelle malibu', 'buick skylark 320',
       'plymouth satellite', 'amc rebel sst', 'ford torino'], dtype='<U26')

In [ ]:
#accessing horsepower
car_hp_arr[1]

array(['130', '165', '150', '150', '140'], dtype='<U26')

In [ ]:
#accessing second car
car_hp_arr[0,1]

np.str_('buick skylark 320')

In [ ]:
#accessing name of the last car
car_hp_arr[0,-1]

np.str_('ford torino')

### Slicing

In [ ]:
#slicing from 1d array
cars=np.array(['cheverolet chevelle malibu', 'buick skylark 320', 'plymouth satellite', 'amc rebel sst', 'ford torino'])

cars[1:4]

array(['buick skylark 320', 'plymouth satellite', 'amc rebel sst'],
      dtype='<U26')

In [ ]:
#slicing from 2d array
car_names=np.array(['cheverolet chevelle malibu', 'buick skylark 320', 'plymouth satellite', 'amc rebel sst', 'ford torino'])
horsepower = [130, 165, 150, 150, 140]
acceleration = [18, 15, 18, 16, 17]

car_hp_acc_arr = np.array([car_names, horsepower, acceleration])
car_hp_acc_arr

array([['cheverolet chevelle malibu', 'buick skylark 320',
        'plymouth satellite', 'amc rebel sst', 'ford torino'],
       ['130', '165', '150', '150', '140'],
       ['18', '15', '18', '16', '17']], dtype='<U26')

In [ ]:
#accessing name and horsepower
car_hp_acc_arr[0:2]

array([['cheverolet chevelle malibu', 'buick skylark 320',
        'plymouth satellite', 'amc rebel sst', 'ford torino'],
       ['130', '165', '150', '150', '140']], dtype='<U26')

In [ ]:
#accessing name and horsepower of last two cars
car_hp_acc_arr[0:2, 3:5]

array([['amc rebel sst', 'ford torino'],
       ['150', '140']], dtype='<U26')

In [ ]:
#accessing name, horsepower and acceleartion of first 3 cars
car_hp_acc_arr[0:3, 0:3]

array([['cheverolet chevelle malibu', 'buick skylark 320',
        'plymouth satellite'],
       ['130', '165', '150'],
       ['18', '15', '18']], dtype='<U26')

### Mean and Median

In [ ]:
horsepower = [130, 165, 150, 150, 140]
horsepower_arr=np.array(horsepower)

#mean horsepower
np.mean(horsepower_arr)

np.float64(147.0)

In [ ]:
#median horsepower
np.median(horsepower_arr)

np.float64(150.0)

### Min & Max

In [ ]:
np.min(horsepower_arr)

np.int64(130)

In [ ]:
np.max(horsepower_arr)

np.int64(165)

In [ ]:
#finding index of min and max values
np.argmin(horsepower_arr)

np.int64(0)

In [ ]:
np.argmax(horsepower_arr)

np.int64(1)

### Querying/Searching in an array

In [ ]:
horsepower = [130, 165, 150, 150, 140]
horsepower_arr=np.array(horsepower)

x = np.where(horsepower_arr >=150)
#gives the indices
print(x)
#with indices values can be found
horsepower_arr[x]

(array([1, 2, 3]),)


array([165, 150, 150])

### Filtering Data

In [ ]:
horsepower = [130, 165, 150, 150, 140]
horsepower_arr=np.array(horsepower)

filter_arr = horsepower_arr>135
newarr = horsepower_arr[filter_arr]

print(filter_arr)
print(newarr)

[False  True  True  True  True]
[165 150 150 140]


### sorting an array

In [ ]:
horsepower = [130, 165, 150, 150, 140]
horsepower_arr=np.array(horsepower)

print('Original Array: ',horsepower_arr)
print('Sorted Array: ',np.sort(horsepower_arr))
print('Original Array after sorting : ',horsepower_arr)

Original Array:  [130 165 150 150 140]
Sorted Array:  [130 140 150 150 165]
Original Array after sorting :  [130 165 150 150 140]


In [ ]:
horsepower = [130, 165, 150, 150, 140]
horsepower_arr=np.array(horsepower)

print('Original Array: ',horsepower_arr)
horsepower_arr.sort()
print('Original Array after sorting : ',horsepower_arr)

Original Array:  [130 165 150 150 140]
Original Array after sorting :  [130 140 150 150 165]


array.sort(): modifies the original array by default <br>
sort(array): does not modify the original array by default

### Vectorized operations

Numpy makes use of optimized, pre-compiled code to perform mathematical operations on each array element. This eliminates the need of using loops, thereby enhancing the performance. This process is called vectorization.

In [ ]:
student_marks_arr=np.array([78, 92, 36, 64, 89])
print(np.sum(student_marks_arr))

359


In [ ]:
#award extra marks in each subject
additional_marks = [2,2,5,10,1]
student_marks_arr+=additional_marks
student_marks_arr

array([80, 94, 41, 74, 90])

In [ ]:
student_marks_arr=np.array([78, 92, 36, 64, 89])
additional_marks = [2,2,5,10,1]
student_marks_arr = np.add(student_marks_arr,additional_marks)
student_marks_arr

array([80, 94, 41, 74, 90])

### Broadcasting

In [ ]:
array1=np.array([5,10,15])
array2=np.array([5])
#array2 is being streched to match array1 resulting in new array with the same shape as array1
array3=array1*array2
array3

array([25, 50, 75])

In [ ]:
#students marks in 4 subjects
students_marks = np.array([[67, 45],[90, 92],[66, 72],[32, 40]])
students_marks

array([[67, 45],
       [90, 92],
       [66, 72],
       [32, 40]])

In [ ]:
#adding 5 marks in 1st sub and 10 marks in 2nd sub
students_marks+=[5,10]
students_marks

array([[ 72,  55],
       [ 95, 102],
       [ 71,  82],
       [ 37,  50]])

### Image as a Numpy matrix

In [ ]:
import os.path
from skimage.io import imread
from skimage import data_dir
img = imread('Astronaut.jpg')

In [ ]:
#using matplotlib.pyplot to visualise the image
import matplotlib.pyplot as plt
plt.imshow(img)

In [ ]:
#viewing as matrix
print(img)

In [ ]:
#properties of image
print('Type of image: ',type(img))
print('Dimensions of image: ',img.ndim)
print('Shape of image: ',img.shape)

In [ ]:
#cutting the rocket out of the image
import os.path
from skimage.io import imread
from skimage import data_dir

#reading the astronaut image
img = imread(os.path.join(data_dir, 'astronaut.jpg'))

#slicing out the rocket
img_slice = img.copy()
img_slice=img_slice[0:300,360:480]
plt.figure()
plt.imshow(img_slice)

In [ ]:
#assigning the values corresponding to the sliced image as 0
img[0:300, 360:480,:]=0
plt.imshow(img)

In [ ]:
img_slice[np.greater_eql(img_slice[:,:,0],100)&np.less_equal(img_slice[:,:,0],150)]=0
plt.figure()
plt.imshow(img_slice)

In [ ]:
#replacing rocket back to its original place
img[0:300,360:480,:]=img_slice
plt.imshow(img)

### Additional Methods
1. arange
2. linspace
3. zeros & ones
4. full & eye
5. random

In [ ]:
#Arange
#start and end limit
np.arange(0,10000)

array([   0,    1,    2, ..., 9997, 9998, 9999])

In [ ]:
#step value 2
np.arange(0,10,2)

array([0, 2, 4, 6, 8])

In [ ]:
#Linspace
#generating values between 0 and 10
arr=np.linspace(0,10)
print(arr)
print('Length of arr: ',len(arr))

[ 0.          0.20408163  0.40816327  0.6122449   0.81632653  1.02040816
  1.2244898   1.42857143  1.63265306  1.83673469  2.04081633  2.24489796
  2.44897959  2.65306122  2.85714286  3.06122449  3.26530612  3.46938776
  3.67346939  3.87755102  4.08163265  4.28571429  4.48979592  4.69387755
  4.89795918  5.10204082  5.30612245  5.51020408  5.71428571  5.91836735
  6.12244898  6.32653061  6.53061224  6.73469388  6.93877551  7.14285714
  7.34693878  7.55102041  7.75510204  7.95918367  8.16326531  8.36734694
  8.57142857  8.7755102   8.97959184  9.18367347  9.3877551   9.59183673
  9.79591837 10.        ]
Length of arr:  50


In [ ]:
#number of values = 3
print(np.linspace(0,10,3))

[ 0.  5. 10.]


In [ ]:
#zeroes: returns an array of given shape filled with zeroes
np.zeros(5)

array([0., 0., 0., 0., 0.])

In [ ]:
#2d
np.zeros([2,3])

array([[0., 0., 0.],
       [0., 0., 0.]])

In [ ]:
#ones: returns an array of given shape filled with ones
np.ones(3)

array([1., 1., 1.])

In [ ]:
#2d
np.ones([2,1])

array([[1.],
       [1.]])

In [ ]:
#full: returns an array of given shape, filled with given value, irrespective of datatype

#number=5, value=8
np.full(5,8)

array([8, 8, 8, 8, 8])

In [ ]:
#shape=[3,3], value=numpy
np.full([3,3],'numpy')

array([['numpy', 'numpy', 'numpy'],
       ['numpy', 'numpy', 'numpy'],
       ['numpy', 'numpy', 'numpy']], dtype='<U5')

In [ ]:
#eye: returns an identity matrix for the given shape

#3x3 identity matrix
np.eye(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [ ]:
#Random

#generating 5 random numbers from a uniform distribution
np.random.rand(5)

array([0.35813661, 0.08361347, 0.64770582, 0.72818694, 0.91174001])

In [ ]:
#random integer valuws low=1, high=1, number of values=5
np.random.randint(1,10, size=5)

array([6, 5, 6, 1, 7])

In [ ]:
#random integer values high=100, shape=(3,5)
x = np.random.randint(100,size=(3,5))
print(x)
print(type(x))

[[86 53  2 94 68]
 [50 38 61 94 87]
 [98 43 55 19 24]]
<class 'numpy.ndarray'>


In [ ]:
#choice: takes array as paramater and randomly returns values based on the size
x=np.random.choice([9,3,7,5])
print(x)

7


In [ ]:
#returns 3*5 random values from the array
x = np.random.choice([9,3,7,5], size=(3,5))
print(x)
print(type(x))

[[7 5 7 9 5]
 [5 7 3 9 3]
 [3 5 5 3 9]]
<class 'numpy.ndarray'>


### Exercise

1. Represent the data in a 10x2 array. Ine ach row, the first element should contain day number and second element should contain steps walked.
2. Lee notices that the tracker's battery dies everyday at 7pm. Lee discovers that on an average, he walks 2000 steps every day after 7pm. Perform an appropriate operation on your array to add 2000 steps to all the observations.
3. Write a program that returns the steps walked if the steps walked are more than 9000
4. Print an array containing steps walked in sorted order

In [ ]:
day_step_arr= np.array([[1,6012],[2,7079],[3,6886],[4,7230],[5,4598],[6,5564],[7,6971],[8,7763],[9,8032],[10,9569]])
day_step_arr.shape

(10, 2)

In [ ]:
add_steps=np.array([0,2000])
day_step_arr+=add_steps
day_step_arr

array([[    1,  8012],
       [    2,  9079],
       [    3,  8886],
       [    4,  9230],
       [    5,  6598],
       [    6,  7564],
       [    7,  8971],
       [    8,  9763],
       [    9, 10032],
       [   10, 11569]])

In [ ]:
filter_arr = np.where(day_step_arr[:,1]>9000)
print(day_step_arr[filter_arr][:,1])

[ 9079  9230  9763 10032 11569]


In [ ]:
steps_arr = day_step_arr[:,1]
steps_arr.sort()
steps_arr

array([ 6598,  7564,  8012,  8886,  8971,  9079,  9230,  9763, 10032,
       11569])